# 定义路由规则
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: 
  name: bookinfo-ratings
  namespace: test
spec: 
  host: bookinfo-ratings
  subsets:
  - name: v1
    labels: 
      version: v1


# 定义virtualSerice
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bookinfo-ratings
  namespace: test
spec:
  hosts:
  - bookinfo-ratings
  http:
  - fault:
      abort:
        percentage:
          value: 50
        httpStatus: 500
    route:
    - destination:
        host: bookinfo-ratings
        subset: v1