apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjcnBpLWJic3l3OXd5NmozOXVmaWEuY24tYmVpamluZy5wZXJzb25hbC5jci5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJmdXR1cmVfd3dsIiwicGFzc3dvcmQiOiIzMjExMDIxOW1pa3UiLCJlbWFpbCI6InRpZ2VyQGFjbWUuZXhhbXBsZSIsImF1dGgiOiJablYwZFhKbFgzZDNiRG96TWpFeE1ESXhPVzFwYTNVPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2025-04-20T14:18:15Z"
  name: secret-tiger-docker
  namespace: springboot
  resourceVersion: "2499"
  uid: 43f744d4-bd96-40d4-a6f2-0554b036e2f4
type: kubernetes.io/dockerconfigjson


# kubernetes拉取私仓镜像时需设置secret
# 创建镜像拉取秘钥：
# kubectl create secret docker-registry secret-tiger-docker \
#   --docker-email=tiger@acme.example \
#   --docker-username=admin \
#   --docker-password=Harbor12345 \
#   --docker-server=harbor.com
