apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: bookinfo-productpage
  namespace: test
spec:
  host: bookinfo-productpage
  trafficPolicy: 
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1