---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bookinfo.com
  resources:
  - bookinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bookinfo.com
  resources:
  - bookinfoes/finalizers
  verbs:
  - update
- apiGroups:
  - bookinfo.com
  resources:
  - bookinfoes/status
  verbs:
  - get
  - patch
  - update
