resources:
- ../base
namePrefix: weilai-
nameSuffix: -dev
namespace: test
commonLabels:
  app: bookinfo
images:
- name: bookinfo
  newName: harbor.com/containers/bookinfo
  newTag: v1.3

patches:
- path: set_memory.yaml

- target: 
    version: v1
    group: networking.k8s.io
    kind: Ingress
    name: bookinfo
  path: set_host.yaml

# kubectl 1.20 使用
# bases:
# - ../base/

# namePrefix: weilai-
# nameSuffix: -dev
# namespace: test
# commonLabels:
#   app: bookinfo
# images:
# - name: bookinfo
#   newName: harbor.com/containers/bookinfo
#   newTag: v1.3

# patchesStrategicMerge:
# - set_memory.yaml

# patchesJson6902:
# - target:
#     version: v1
#     group: networking.k8s.io
#     kind: Ingress
#     name: bookinfo
#   path: set_host.yaml