volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:

  prometheus:
    container_name: prometheus
    # image: prom/prometheus:v2.53.1
    image: harbor.com/containers/prom_prometheus:v2.53.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
      - pushgateway:pushgateway
    depends_on:
      - cadvisor
      - pushgateway
    networks:
      - back-tier
    restart: always



  alertmanager:
    container_name: alertmanager
    # image: prom/alertmanager:v0.27.0
    image: harbor.com/containers/prom_alertmanager:v0.27.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    container_name: grafana
    image: harbor.com/containers/grafana_grafana:10.0.0
    # image: grafana/grafana:10.0.0
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 9094:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always

  pushgateway:
    container_name: pushgateway
    # image: prom/pushgateway:v1.9.0
    image: harbor.com/containers/prom_pushgateway:v1.9.0
    restart: always
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - back-tier
  cadvisor:
    container_name: cadvisor
    # image: google/cadvisor:v0.33.0
    image: harbor.com/containers/google_cadvisor:v0.33.0
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9092:8080
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global