apiVersion: v1
kind: Service
metadata: 
   name: bookinfo-details
   labels:
      app: bookinfo-details
spec: 
  selector:
   app: bookinfo-details
  ports: 
  - name: web
    port: 80
    targetPort: 8080
