apiVersion: v1
kind: Service
metadata: 
   name: bookinfo-productpage
   labels:
      app: bookinfo-productpage
spec: 
  selector:
   app: bookinfo-productpage
  ports: 
  - name: web
    port: 80
    targetPort: 8080
