apiVersion: v1
kind: Service
metadata: 
   name: bookinfo-reviews
   labels:
      app: bookinfo-reviews
spec: 
  selector:
   app: bookinfo-reviews
  ports: 
  - name: web
    port: 80
    targetPort: 8080
