FROM --platform=$BUILDPLATFORM harbor.imooc.com/imooc-containers/golang:1.22.3-alpine3.20 as builder
ARG TARGETARCH
WORKDIR /
COPY . .
RUN [ ! -d "vendor" ] && go env -w GOPROXY=https://goproxy.cn,direct || echo "skipping"
RUN if [ "$TARGETARCH" = "arm64"];then \ 
   go env -w GOARCH="arm64"; \
   fi
RUN go build -o bk

FROM harbor.imooc.com/imooc-containers/alpine:3.20-bookinfo-base
WORKDIR /
COPY templates /templates
COPY static /static
COPY --from=builder /bk /
ENTRYPOINT [ "/bk","serve"]
