build:
	cd web && make build TAG=v1.5;
	cd reviews && make build TAG=v1.5;
	cd ratings && make build TAG=v1.5;
	cd productpage && make build TAG=v1.5;
	cd details && make build TAG=v1.5;

buildbuildx: 
	cd web && make buildx TAG=v1.5;
	cd reviews && make buildx TAG=v1.5;
	cd ratings && make buildx TAG=v1.5;
	cd productpage && make buildx TAG=v1.5
	cd details && make buildx TAG=v1.5;

