build:
	cd web && make build;
	cd reviews && make build;
	cd ratings && make build;
	cd productpage && make build;
	cd details && make build;

buildbuildx: 
	cd web && make buildx;
	cd reviews && make buildx;
	cd ratings && make buildx;
	cd productpage && make buildx;
	cd details && make buildx;