# 定义路由规则
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: 
  name: bookinfo-reviews
  namespace: test
spec: 
  host: bookinfo-reviews
  subsets:
  - name: v1
    labels: 
      version: v1
  - name: v2
    labels: 
      version: v2


# 定义virtualSerice
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bookinfo-reviews
  namespace: test
spec:
  hosts:
  - bookinfo-reviews
  http:
  - route:
    - destination:
        host: bookinfo-reviews
        subset: v2
