apiVersion: apps/v1
kind: Deployment
metadata: 
   name: bookinfo-details
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: bookinfo-details
  template:
    metadata: 
      labels: 
        app: bookinfo-details
    spec: 
      imagePullSecrets:
      - name: secret-tiger-docker
      containers: 
      - name: bookinfo-details
        image: bookinfo-details
        imagePullPolicy: Always
        ports: 
        - name: web
          containerPort: 8080
        volumeMounts: 
        - name: cfg
          mountPath: /cfg
      volumes:
      - name: cfg
        configMap:
           name: bookinfo-cfg

