apiVersion: apps/v1
kind: Deployment
metadata: 
   name: bookinfo-ratings
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: bookinfo-ratings
  template:
    metadata: 
      labels: 
        app: bookinfo-ratings
    spec: 
      imagePullSecrets:
      - name: secret-tiger-docker
      containers: 
      - name: bookinfo-ratings
        image: bookinfo-ratings
        imagePullPolicy: Always
        ports: 
        - name: web
          containerPort: 8080
        volumeMounts: 
        - name: cfg
          mountPath: /cfg
      volumes:
      - name: cfg
        configMap:
           name: bookinfo-cfg
