global:
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: '10000@qq.com'
  smtp_auth_username: '10000@qq.com'
  smtp_auth_password: ''
  smtp_require_tls: false

route:
  receiver: 'qq-email'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'qq-email'
    email_configs:
      - to: '10000@qq.com'
        send_resolved: true
