resources:
- ../base
# namePrefix: weilai-
# nameSuffix: -dev
namespace: test
commonLabels:
  team: weilai
images: 
- name: bookinfo-web
  newName: crpi-bbsyw9wy6j39ufia.cn-beijing.personal.cr.aliyuncs.com/containers-wwl/bookinfo-web
  newTag: v1.5
- name: bookinfo-reviews
  newName: crpi-bbsyw9wy6j39ufia.cn-beijing.personal.cr.aliyuncs.com/containers-wwl/bookinfo-reviews
  newTag: v1.5
- name: bookinfo-ratings
  newName: crpi-bbsyw9wy6j39ufia.cn-beijing.personal.cr.aliyuncs.com/containers-wwl/bookinfo-ratings
  newTag: v1.5
- name: bookinfo-productpage
  newName: crpi-bbsyw9wy6j39ufia.cn-beijing.personal.cr.aliyuncs.com/containers-wwl/bookinfo-productpage
  newTag: v1.5
- name: bookinfo-details
  newName: crpi-bbsyw9wy6j39ufia.cn-beijing.personal.cr.aliyuncs.com/containers-wwl/bookinfo-details
  newTag: v1.5
patches:
- path: set_memory.yaml
- target: 
    version: v1
    group: networking.k8s.io
    kind: Ingress
    name: bookinfo
  path: set_host.yaml
